"""
    Bundesagentur für Arbeit: Coachingangebote API

    Eine der größten Datenbanken zu Coaching-/Aktivierungsangeboten Deutschlands durchsuchen.   Die Authentifizierung funktioniert per OAuth 2 Client Credentials mit JWTs. Folgende Client-Credentials können dafür verwendet werden:  **ClientID:** ee971dcb-96fa-47b3-b2be-00863e4fc88b  **ClientSecret:** 1050e0b7-6db8-49e8-aff9-0e58e556681f  **Achtung**: der generierte Token muss bei folgenden GET-requests im header als 'OAuthAccessToken' inkludiert werden.    # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: andreasfischer1985@web.de
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from deutschland.coachingangebote.exceptions import ApiAttributeError
from deutschland.coachingangebote.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    OpenApiModel,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


def lazy_import():
    from deutschland.coachingangebote.model.response_embedded_termine_inner_abstaende_inner import (
        ResponseEmbeddedTermineInnerAbstaendeInner,
    )
    from deutschland.coachingangebote.model.response_embedded_termine_inner_adresse import (
        ResponseEmbeddedTermineInnerAdresse,
    )
    from deutschland.coachingangebote.model.response_embedded_termine_inner_angebot import (
        ResponseEmbeddedTermineInnerAngebot,
    )
    from deutschland.coachingangebote.model.response_embedded_termine_inner_ansprechpartner_inner import (
        ResponseEmbeddedTermineInnerAnsprechpartnerInner,
    )
    from deutschland.coachingangebote.model.response_embedded_termine_inner_unterrichtsform import (
        ResponseEmbeddedTermineInnerUnterrichtsform,
    )

    globals()[
        "ResponseEmbeddedTermineInnerAbstaendeInner"
    ] = ResponseEmbeddedTermineInnerAbstaendeInner
    globals()[
        "ResponseEmbeddedTermineInnerAdresse"
    ] = ResponseEmbeddedTermineInnerAdresse
    globals()[
        "ResponseEmbeddedTermineInnerAngebot"
    ] = ResponseEmbeddedTermineInnerAngebot
    globals()[
        "ResponseEmbeddedTermineInnerAnsprechpartnerInner"
    ] = ResponseEmbeddedTermineInnerAnsprechpartnerInner
    globals()[
        "ResponseEmbeddedTermineInnerUnterrichtsform"
    ] = ResponseEmbeddedTermineInnerUnterrichtsform


class ResponseEmbeddedTermineInner(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {}

    validations = {}

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (
            bool,
            date,
            datetime,
            dict,
            float,
            int,
            list,
            str,
            none_type,
        )  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            "id": (int,),  # noqa: E501
            "massnahme_nummer": (str,),  # noqa: E501
            "angebot": (ResponseEmbeddedTermineInnerAngebot,),  # noqa: E501
            "adresse": (ResponseEmbeddedTermineInnerAdresse,),  # noqa: E501
            "unterrichtsform": (
                ResponseEmbeddedTermineInnerUnterrichtsform,
            ),  # noqa: E501
            "gueltig_von": (int,),  # noqa: E501
            "gueltig_bis": (int,),  # noqa: E501
            "massnahme_zeiten": (str,),  # noqa: E501
            "individueller_einstieg": (bool,),  # noqa: E501
            "bemerkung_zeit": (str,),  # noqa: E501
            "zusatzlink": (str,),  # noqa: E501
            "ansprechpartner": (
                [ResponseEmbeddedTermineInnerAnsprechpartnerInner],
            ),  # noqa: E501
            "aktualisierungsdatum": (int,),  # noqa: E501
            "abstaende": ([ResponseEmbeddedTermineInnerAbstaendeInner],),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None

    attribute_map = {
        "id": "id",  # noqa: E501
        "massnahme_nummer": "massnahmeNummer",  # noqa: E501
        "angebot": "angebot",  # noqa: E501
        "adresse": "adresse",  # noqa: E501
        "unterrichtsform": "unterrichtsform",  # noqa: E501
        "gueltig_von": "gueltigVon",  # noqa: E501
        "gueltig_bis": "gueltigBis",  # noqa: E501
        "massnahme_zeiten": "massnahmeZeiten",  # noqa: E501
        "individueller_einstieg": "individuellerEinstieg",  # noqa: E501
        "bemerkung_zeit": "bemerkungZeit",  # noqa: E501
        "zusatzlink": "zusatzlink",  # noqa: E501
        "ansprechpartner": "ansprechpartner",  # noqa: E501
        "aktualisierungsdatum": "aktualisierungsdatum",  # noqa: E501
        "abstaende": "abstaende",  # noqa: E501
    }

    read_only_vars = {}

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """ResponseEmbeddedTermineInner - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (int): [optional]  # noqa: E501
            massnahme_nummer (str): [optional]  # noqa: E501
            angebot (ResponseEmbeddedTermineInnerAngebot): [optional]  # noqa: E501
            adresse (ResponseEmbeddedTermineInnerAdresse): [optional]  # noqa: E501
            unterrichtsform (ResponseEmbeddedTermineInnerUnterrichtsform): [optional]  # noqa: E501
            gueltig_von (int): [optional]  # noqa: E501
            gueltig_bis (int): [optional]  # noqa: E501
            massnahme_zeiten (str): [optional]  # noqa: E501
            individueller_einstieg (bool): [optional]  # noqa: E501
            bemerkung_zeit (str): [optional]  # noqa: E501
            zusatzlink (str): [optional]  # noqa: E501
            ansprechpartner ([ResponseEmbeddedTermineInnerAnsprechpartnerInner]): [optional]  # noqa: E501
            aktualisierungsdatum (int): [optional]  # noqa: E501
            abstaende ([ResponseEmbeddedTermineInnerAbstaendeInner]): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop("_check_type", True)
        _spec_property_naming = kwargs.pop("_spec_property_naming", True)
        _path_to_item = kwargs.pop("_path_to_item", ())
        _configuration = kwargs.pop("_configuration", None)
        _visited_composed_classes = kwargs.pop("_visited_composed_classes", ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments."
                        % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if (
                var_name not in self.attribute_map
                and self._configuration is not None
                and self._configuration.discard_unknown_keys
                and self.additional_properties_type is None
            ):
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set(
        [
            "_data_store",
            "_check_type",
            "_spec_property_naming",
            "_path_to_item",
            "_configuration",
            "_visited_composed_classes",
        ]
    )

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """ResponseEmbeddedTermineInner - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (int): [optional]  # noqa: E501
            massnahme_nummer (str): [optional]  # noqa: E501
            angebot (ResponseEmbeddedTermineInnerAngebot): [optional]  # noqa: E501
            adresse (ResponseEmbeddedTermineInnerAdresse): [optional]  # noqa: E501
            unterrichtsform (ResponseEmbeddedTermineInnerUnterrichtsform): [optional]  # noqa: E501
            gueltig_von (int): [optional]  # noqa: E501
            gueltig_bis (int): [optional]  # noqa: E501
            massnahme_zeiten (str): [optional]  # noqa: E501
            individueller_einstieg (bool): [optional]  # noqa: E501
            bemerkung_zeit (str): [optional]  # noqa: E501
            zusatzlink (str): [optional]  # noqa: E501
            ansprechpartner ([ResponseEmbeddedTermineInnerAnsprechpartnerInner]): [optional]  # noqa: E501
            aktualisierungsdatum (int): [optional]  # noqa: E501
            abstaende ([ResponseEmbeddedTermineInnerAbstaendeInner]): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop("_check_type", True)
        _spec_property_naming = kwargs.pop("_spec_property_naming", False)
        _path_to_item = kwargs.pop("_path_to_item", ())
        _configuration = kwargs.pop("_configuration", None)
        _visited_composed_classes = kwargs.pop("_visited_composed_classes", ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments."
                        % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if (
                var_name not in self.attribute_map
                and self._configuration is not None
                and self._configuration.discard_unknown_keys
                and self.additional_properties_type is None
            ):
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(
                    f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                    f"class with read only attributes."
                )
